### ISSUE TITLE
Multiple matches on a single line

### ISSUE THREAD

**Issue by nickasd** [i18next/i18next-parser#100]
- Is this a bug or a feature request? Bug
- What version are you running (`0.x` or `1.x`)? 1.0-beta14
- Which runner (cli, gulp...)? gulp

## What I'm trying to do?

I'm trying to extract this Handlebars template:
```
{{_ 'key1' 'value1'}} some text {{_ 'key2' 'value2'}}
```

## What was the result?

Only key1 appears in the output json file.

## What was I expecting?

I expected key2 to appear as well.

If this is not on purpose, the lexers would have to be slightly changed. For instance, in the Handlebars lexer, the part `(.*)` in the variable `curlyPattern` would have to be changed to `(.*?)` so that matches are non-greedy.

**Comment by karellm** [comment]
Addressed in `1.0.0-beta16`

**Comment by nickasd** [comment]
After updating to 1.0.0-beta16 I have the following error:
```
Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nicolaskick/Documents/events/server/node_modules/i18next-parser/dist/broccoli.js:2:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

I think this was introduced in beta15 and it's because the package `fs-extra` should be moved from devDependencies to dependencies, or did I miss something?
